Repository roadrunner-server/roadrunner, pull requests merged in 2020-12, with the labels that each got.

#423 [RR2] PHP 8.0 support
  .github/workflows/ci-build.yml
  bors.toml
  composer.json
  composer.lock
  plugins/http/tests/handler_test.go
  plugins/http/tests/http_test.go
  plugins/static/tests/static_plugin_test.go
  static_pool_test.go
Labels: A-other

#424 Release 1.9.0
  .github/workflows/ci-build.yml
  CHANGELOG.md
  Dockerfile
  bors.toml
  build.sh
  service/http/handler_test.go
  service/limit/service_test.go
Labels: C-enhancement

#428 Checker plugin
  .github/workflows/ci-build.yml
  Makefile
  codecov.yml
  go.mod
  go.sum
  interfaces/informer/interface.go
  interfaces/status/interface.go
  plugins/checker/config.go
  plugins/checker/plugin.go
  plugins/checker/rpc.go
  plugins/checker/tests/configs/.rr-checker-init.yaml
  plugins/checker/tests/plugin_test.go
  plugins/http/plugin.go
  plugins/informer/plugin.go
  sync_worker_test.go
  util/events.go
Labels: A-module

#433 Releases and binaries build automation
  .github/workflows/codeql-analysis.yml
  .github/workflows/release.yml
  Dockerfile
  Makefile
  bin/rr
  build.sh
  composer.json
Labels: A-ci

#437 GitHub actions updated
  .github/workflows/build.yml
  .github/workflows/ci-build.yml
  .gitignore
  Makefile
  bors.toml
  composer.json
  phpstan.neon.dist
  src/Diactoros/ServerRequestFactory.php
  src/Diactoros/StreamFactory.php
  src/Diactoros/UploadedFileFactory.php
  src/HttpClient.php
Labels: A-ci

#438 Add `rr --version` flag
  CHANGELOG.md
  cmd/rr/cmd/root.go
Labels: A-other

#441 dependabot.yml
  .github/dependabot.yml
Labels: A-ci

#442 Add objectives to the metrics summary
  .rr.yaml
  service/metrics/config.go
  service/metrics/config_test.go
  service/metrics/rpc.go
Labels: A-metrics

#451 [RR2] Remove PHP code
  tests/composer.json
  tests/src/Environment.php
  tests/src/EnvironmentInterface.php
  tests/src/Exception/EnvironmentException.php
  tests/src/Exception/RoadRunnerException.php
  tests/src/Http/HttpWorker.php
  tests/src/Http/PSR7Worker.php
  tests/src/Http/Request.php
  tests/src/Payload.php
  tests/src/Worker.php
  tests/src/WorkerInterface.php
Labels: A-other, C-enhancement

#452 Refactor/split
  .github/workflows/build.yml
  Makefile
  go.sum
  interfaces/events/handler.go
  interfaces/events/pool_events.go
  interfaces/events/worker_events.go
  interfaces/factory/factory.go
  interfaces/informer/interface.go
  interfaces/pool/pool.go
  interfaces/server/interface.go
  interfaces/worker/factory.go
  interfaces/worker/watcher.go
  interfaces/worker/worker.go
  internal/payload.go
  internal/protocol.go
  internal/state.go
  internal/state_test.go
  pipe_factory_test.go
  pkg/events/events.go
  pkg/pipe/pipe_factory.go
  pkg/pipe/pipe_factory_test.go
  pkg/pool/config.go
  pkg/pool/static_pool.go
  pkg/pool/static_pool_test.go
  pkg/pool/supervisor_pool.go
  pkg/pool/supervisor_test.go
  pkg/socket/socket_factory.go
  pkg/socket/socket_factory_test.go
  pkg/worker/sync_worker.go
  pkg/worker/sync_worker_test.go
  pkg/worker/worker.go
  pkg/worker/worker_test.go
  pkg/worker_watcher/worker_watcher.go
  plugins/http/config.go
  plugins/http/handler.go
  plugins/http/plugin.go
  plugins/http/request.go
  plugins/http/response.go
  plugins/http/tests/configs/.rr-http.yaml
  plugins/http/tests/handler_test.go
  plugins/http/tests/http_test.go
  plugins/http/tests/response_test.go
  plugins/http/tests/uploads_test.go
  plugins/informer/plugin.go
  plugins/informer/tests/test_plugin.go
  plugins/reload/tests/reload_plugin_test.go
  plugins/resetter/tests/test_plugin.go
  plugins/server/plugin.go
  plugins/server/tests/plugin_pipes.go
  plugins/server/tests/plugin_sockets.go
  plugins/server/tests/plugin_tcp.go
  process.go
  state_test.go
  sync_worker_test.go
  util/events.go
  worker.go
  worker_test.go
Labels: A-other, C-enhancement

#455 plugin/reload fixes
  .github/workflows/build.yml
  codecov.yml
  pipe_factory.go
  service/reload/samefile.go
  service/reload/samefile_windows.go
  service/reload/service.go
  service/reload/service_test.go
  service/reload/watcher.go
  service/reload/watcher_test.go
Labels: A-module

#456 Reload/tests stabilization
  .github/workflows/build.yml
  go.mod
  go.sum
  interfaces/worker/worker.go
  internal/protocol.go
  pkg/pipe/pipe_factory.go
  pkg/pipe/pipe_factory_test.go
  pkg/socket/socket_factory.go
  pkg/worker/sync_worker.go
  pkg/worker/worker.go
  plugins/checker/tests/plugin_test.go
  plugins/http/tests/http_test.go
  plugins/informer/tests/informer_test.go
  plugins/metrics/tests/metrics_test.go
  plugins/reload/tests/reload_plugin_test.go
  plugins/resetter/tests/resetter_test.go
  plugins/rpc/plugin.go
  plugins/rpc/tests/plugin2.go
Labels: A-tests

#453 Plugin/redis
  .github/workflows/build.yml
  .rr.yaml
  Makefile
  go.mod
  go.sum
  interfaces/config/interface.go
  interfaces/factory/factory.go
  interfaces/pool/pool.go
  interfaces/redis/interface.go
  interfaces/worker/factory.go
  interfaces/worker/worker.go
  pkg/pipe/pipe_factory.go
  pkg/pipe/pipe_factory_test.go
  pkg/pool/static_pool.go
  pkg/pool/static_pool_test.go
  pkg/socket/socket_factory.go
  pkg/socket/socket_factory_test.go
  pkg/worker/sync_worker.go
  pkg/worker/worker.go
  pkg/worker_watcher/worker_watcher.go
  plugins/checker/plugin.go
  plugins/config/plugin.go
  plugins/config/tests/plugin1.go
  plugins/headers/plugin.go
  plugins/http/plugin.go
  plugins/http/tests/plugin1.go
  plugins/http/tests/plugin_middleware.go
  plugins/informer/tests/test_plugin.go
  plugins/logger/plugin.go
  plugins/logger/tests/plugin.go
  plugins/metrics/plugin.go
  plugins/metrics/tests/plugin1.go
  plugins/redis/config.go
  plugins/redis/plugin.go
  plugins/redis/tests/plugin1.go
  plugins/redis/tests/redis_plugin_test.go
  plugins/reload/plugin.go
  plugins/resetter/tests/test_plugin.go
  plugins/rpc/plugin.go
  plugins/rpc/tests/plugin1.go
  plugins/server/plugin.go
  plugins/server/tests/plugin_pipes.go
  plugins/server/tests/plugin_sockets.go
  plugins/server/tests/plugin_tcp.go
  plugins/static/plugin.go
Labels: A-module

#459 plugin/redis [reopen]
  go.sum
  plugins/checker/plugin.go
  plugins/config/tests/plugin1.go
  plugins/headers/plugin.go
  plugins/http/plugin.go
  plugins/http/tests/plugin1.go
  plugins/http/tests/plugin_middleware.go
  plugins/informer/tests/test_plugin.go
  plugins/logger/plugin.go
  plugins/logger/tests/plugin.go
  plugins/metrics/plugin.go
  plugins/metrics/tests/plugin1.go
  plugins/reload/plugin.go
  plugins/resetter/tests/test_plugin.go
  plugins/rpc/tests/plugin1.go
  plugins/server/plugin.go
  plugins/server/tests/plugin_pipes.go
  plugins/server/tests/plugin_sockets.go
  plugins/server/tests/plugin_tcp.go
  plugins/static/plugin.go
Labels: A-other

#460 Release 1.9.1
  .github/workflows/build.yml
  CHANGELOG.md
  bors.toml
  composer.json
Labels: A-other

#462 feature/CLI
  .golangci.yml
  .rr.yaml
  cmd/cli/reset.go
  cmd/cli/root.go
  cmd/cli/serve.go
  cmd/cli/workers.go
  cmd/main.go
  go.mod
  go.sum
  interfaces/pool/pool.go
  interfaces/worker/factory.go
  interfaces/worker/worker.go
  pkg/pipe/pipe_factory.go
  pkg/pipe/pipe_factory_test.go
  pkg/pool/static_pool.go
  pkg/pool/static_pool_test.go
  pkg/pool/supervisor_pool.go
  pkg/pool/supervisor_test.go
  pkg/socket/socket_factory.go
  pkg/worker/sync_worker.go
  pkg/worker/worker.go
  pkg/worker_watcher/worker_watcher.go
  tools/process.go
  tools/worker_table.go
Labels: A-other
