Repository roadrunner-server/roadrunner, pull requests merged in 2020-05, with the labels that each got.

#317 Add non-optimized relays support
  src/Worker.php
Labels: A-module, B-regression

#318 release 1.8.0
  .github/workflows/ci-build.yml
  CHANGELOG.md
  bors.toml
  build.sh
  composer.json
  src/HttpClient.php
  src/PSR7Client.php
  src/Worker.php
Labels: A-other

#320 Add support of CloudFlare CF-Connecting-IP and True-Client-IP headers
  service/http/handler.go
Labels: A-network, C-enhancement

#324 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: A-other, C-enhancement

#325 Update feature request templates
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: A-other

#322 fix phpstan based on new goridge interface
  .github/workflows/ci-build.yml
  composer.json
  go.mod
  go.sum
  src/Worker.php
Labels: A-tests, C-enhancement

#327 release 1.8.1
  CHANGELOG.md
  Dockerfile
  build.sh
  cmd/rr/main.go
  service/http/request.go
Labels: A-other, C-enhancement

#323 Add RootCA support
  .rr.yaml
  service/http/config.go
  service/http/service.go
Labels: A-network, C-enhancement

#330 Release 1.8.1
  CHANGELOG.md
  go.mod
  service/http/h2c_test.go
Labels: A-other
