Repository roadrunner-server/roadrunner, pull requests merged in 2020-04, with the labels that each got.

#294 Update composer.json
  composer.json
Labels: A-other, C-enhancement

#295 Vendor directory fix (php vs golang)
  .dockerignore
  .github/workflows/ci-build.yml
  .gitignore
  Makefile
  bors.toml
  composer.json
  service/headers/service_test.go
  tests/client.php
  tests/http/client.php
  tests/http/slow-client.php
  tests/slow-client.php
  tests/slow-destroy.php
Labels: A-other, B-bug

#297 rr.service unit file
  service/limit/service_test.go
  systemd/rr.service
Labels: A-other, C-enhancement, O-linux

#302 Add user to worker
  osutil/isolate.go
  osutil/isolate_win.go
  server_config.go
  service/limit/service_test.go
  static_pool.go
Labels: A-other, C-enhancement, O-linux

#304 remove windows check from sockets tests
  server_config_test.go
  service/http/rpc_test.go
  service/rpc/config_test.go
  socket_factory_test.go
Labels: A-tests, C-enhancement, O-windows

#309 Reduce syscalls usage
  composer.json
  src/Worker.php
Labels: A-other, B-performance

#310 Replace multiple sys_calls with a combined one
  src/Worker.php
Labels: A-other, B-bug, C-enhancement

#311 Release 1.7.1
  .rr.yaml
  CHANGELOG.md
  README.md
  build.sh
Labels: A-other
