Repository roadrunner-server/roadrunner, pull requests merged in 2020-03, with the labels that each got.

#262 Rotate ports
  service/static/service_test.go
Labels: A-tests

#263 Fix for failing tests
  service/static/service_test.go
Labels: A-tests

#265 Signals, typos, concurrency update
  cmd/rr/cmd/serve.go
  go.mod
  go.sum
  service/http/config.go
  service/http/service.go
  service/http/ssl_test.go
  service/rpc/service_test.go
  static_pool_test.go
  util/network_windows.go
  worker.go
Labels: A-network, C-enhancement

#268 Explicitly require Curl since bin/rr doesn't work without it
  composer.json
Labels: C-enhancement

#270 Ub when plugin fail during serve
  .github/workflows/ci-build.yml
  bors.toml
  go.mod
  go.sum
  service/container.go
  service/container_test.go
  service/http/rpc_test.go
  service/http/service_test.go
  service/http/ssl_test.go
Labels: A-ci, A-module, B-bug, C-enhancement

#272 Prepare to 1.6.3 release
  CHANGELOG.md
  build.sh
Labels: A-docs

#273 prepare_to_1_6_3
  CHANGELOG.md
  go.mod
Labels: A-docs

#274 Update Dockerfile labels in favor of OCI spec
  Dockerfile
Labels: A-other, C-enhancement

#282 Replace std json package with github.com/json-iterator/go
  .github/workflows/ci-build.yml
  Makefile
  go.mod
  go.sum
  protocol.go
  service/container_test.go
  service/env/config_test.go
  service/gzip/config_test.go
  service/gzip/service_test.go
  service/headers/config_test.go
  service/headers/service_test.go
  service/health/config_test.go
  service/health/service_test.go
  service/http/config_test.go
  service/http/handler_test.go
  service/http/request.go
  service/http/response.go
  service/http/rpc_test.go
  service/http/service_test.go
  service/http/uploads.go
  service/http/uploads_test.go
  service/limit/config_test.go
  service/limit/service_test.go
  service/metrics/config_test.go
  service/metrics/service_test.go
  service/rpc/config_test.go
  service/static/config_test.go
  service/static/service_test.go
Labels: A-other, B-performance, C-enhancement

#287 release 1.7.0
  CHANGELOG.md
  build.sh
Labels: C-enhancement

#288 Update goridge to 2.3.0 with v2 support
  go.mod
  go.sum
Labels: A-other, C-enhancement

#289 Update to v2
  go.mod
  go.sum
  pipe_factory.go
  protocol.go
  protocol_test.go
  service/rpc/service.go
  socket_factory.go
  worker.go
Labels: A-other, C-enhancement

#291 Update servers timeouts and max header sizes [health, metrics]
  go.mod
  go.sum
  service/headers/service_test.go
  service/health/service.go
  service/http/service_test.go
  service/metrics/service.go
Labels: B-bug
