Repository roadrunner-server/roadrunner, pull requests merged in 2020-11, with the labels that each got.

#380 Switch from Endure errors to the Spiral errors package
  Makefile
  go.mod
  go.sum
  plugins/app/app.go
  plugins/rpc/rpc.go
Labels: C-enhancement

#388 Tests for the new plugins
  .dockerignore
  .github/workflows/ci-build.yml
  .rr.yaml
  Dockerfile
  Makefile
  bors.toml
  composer.lock
  errors/debug_cap.go
  errors/debug_stack.go
  errors/debug_test.go
  errors/errors.go
  errors/marshal.go
  go.mod
  go.sum
  log/interface.go
  log/zap_adapter.go
  phpstan.neon.dist
  pipe_factory.go
  plugins/app/plugin.go
  plugins/app/tests/app_test.go
  plugins/app/tests/configs/.rr-no-app-section.yaml
  plugins/app/tests/configs/.rr-sockets.yaml
  plugins/app/tests/configs/.rr-tcp.yaml
  plugins/app/tests/configs/.rr-wrong-command.yaml
  plugins/app/tests/configs/.rr-wrong-relay.yaml
  plugins/app/tests/configs/.rr.yaml
  plugins/app/tests/hello.php
  plugins/app/tests/plugin_1.go
  plugins/app/tests/plugin_2.go
  plugins/app/tests/plugin_pipes.go
  plugins/app/tests/plugin_sockets.go
  plugins/app/tests/plugin_tcp.go
  plugins/app/tests/socket.php
  plugins/app/tests/tcp.php
  plugins/config/configurer.go
  plugins/config/plugin.go
  plugins/config/tests/.rr.yaml
  plugins/config/tests/config_test.go
  plugins/config/tests/plugin1.go
  plugins/logger/encoder.go
  plugins/logger/plugin.go
  plugins/logger/tests/.rr.yaml
  plugins/logger/tests/logger_test.go
  plugins/logger/tests/plugin.go
  plugins/rpc/plugin.go
  plugins/rpc/tests/.rr-rpc-disabled.yaml
  plugins/rpc/tests/.rr.yaml
  plugins/rpc/tests/plugin1.go
  plugins/rpc/tests/plugin2.go
  plugins/rpc/tests/rpc_test.go
  static_pool.go
  supervisor_pool.go
  sync_worker.go
  worker_watcher.go
Labels: A-tests

#390 Feature/switch to spiral errors
  .github/workflows/ci-build.yml
  errors.go
  errors_test.go
  go.mod
  go.sum
  pipe_factory.go
  plugins/app/plugin.go
  process_state.go
  process_state_test.go
  socket_factory_test.go
  static_pool.go
  static_pool_test.go
  supervisor_pool.go
  sync_worker.go
  sync_worker_test.go
  util/isolate.go
  worker_watcher.go
Labels: C-enhancement

#392 [RR2] Metrics plugin 2.0
  .github/workflows/ci-build.yml
  .golangci.yml
  Makefile
  codecov.yml
  go.mod
  go.sum
  interfaces/log/interface.go
  interfaces/log/zap_adapter.go
  interfaces/metrics/interface.go
  interfaces/rpc/interface.go
  interfaces/server/interface.go
  plugins/logger/plugin.go
  plugins/logger/tests/plugin.go
  plugins/metrics/config.go
  plugins/metrics/config_test.go
  plugins/metrics/doc.go
  plugins/metrics/plugin.go
  plugins/metrics/rpc.go
  plugins/metrics/tests/.rr-test.yaml
  plugins/metrics/tests/docker-compose.yml
  plugins/metrics/tests/metrics_test.go
  plugins/metrics/tests/plugin1.go
  plugins/rpc/plugin.go
  plugins/rpc/tests/plugin1.go
  plugins/server/config.go
  plugins/server/plugin.go
  plugins/server/tests/configs/.rr-no-app-section.yaml
  plugins/server/tests/configs/.rr-sockets.yaml
  plugins/server/tests/configs/.rr-tcp.yaml
  plugins/server/tests/configs/.rr-wrong-command.yaml
  plugins/server/tests/configs/.rr-wrong-relay.yaml
  plugins/server/tests/configs/.rr.yaml
  plugins/server/tests/plugin_pipes.go
  plugins/server/tests/plugin_sockets.go
  plugins/server/tests/plugin_tcp.go
  plugins/server/tests/server_test.go
  plugins/server/tests/socket.php
  plugins/server/tests/tcp.php
  pool.go
  static_pool.go
  static_pool_test.go
  supervisor_pool.go
  supervisor_test.go
  util/events.go
  worker_watcher.go
Labels: A-module

#408 Plugin/informer
  .github/workflows/ci-build.yml
  Makefile
  go.mod
  interfaces/informer/interface.go
  interfaces/server/interface.go
  plugins/informer/plugin.go
  plugins/informer/rpc.go
  plugins/informer/tests/.rr-informer.yaml
  plugins/informer/tests/informer_test.go
  plugins/informer/tests/test_plugin.go
  plugins/metrics/tests/metrics_test.go
  plugins/server/tests/plugin_pipes.go
  plugins/server/tests/plugin_sockets.go
  plugins/server/tests/plugin_tcp.go
Labels: A-module

#409 Plugin/resetter
  .github/workflows/ci-build.yml
  Makefile
  interfaces/resetter/interface.go
  plugins/resetter/plugin.go
  plugins/resetter/rpc.go
  plugins/resetter/tests/.rr-resetter.yaml
  plugins/resetter/tests/resetter_test.go
  plugins/resetter/tests/test_plugin.go
Labels: A-module

#416 Add new pool event: EventNoFreeWorkers
  go.mod
  go.sum
  plugins/http/tests/http_test.go
  pool.go
  static_pool.go
  static_pool_test.go
  supervisor_pool.go
  sync_worker.go
  sync_worker_test.go
  worker_watcher.go
Labels: A-other

#420 [RR2] Plugin for serving static files [Static]
  .github/workflows/ci-build.yml
  .golangci.yml
  Makefile
  plugins/gzip/plugin.go
  plugins/http/plugin.go
  plugins/http/tests/http_test.go
  plugins/static/config.go
  plugins/static/config_test.go
  plugins/static/plugin.go
  plugins/static/tests/configs/.rr-http-static-disabled.yaml
  plugins/static/tests/configs/.rr-http-static-files-disable.yaml
  plugins/static/tests/configs/.rr-http-static-files.yaml
  plugins/static/tests/configs/.rr-http-static.yaml
  plugins/static/tests/static_plugin_test.go
Labels: A-module

#419 Allow PHP 8.0
  .github/workflows/ci-build.yml
  bors.toml
  composer.json
  service/http/handler_test.go
Labels: A-ci, A-tests
