Repository roadrunner-server/roadrunner, pull requests merged in 2020-08, with the labels that each got.

#351 Fix HSTS header
  service/http/service.go
Labels: A-network, C-enhancement

#353 Pci dss upgrade
  README.md
  go.mod
  go.sum
  service/http/service.go
  service/metrics/service.go
  service/reload/watcher_test.go
  worker.go
Labels: A-other, C-enhancement

#345 Adding headers to static files
  .rr.yaml
  service/static/config.go
  service/static/config_test.go
  service/static/service.go
  service/static/service_test.go
Labels: A-network, C-enhancement

#355 Broken pipe issue
  service/http/errors.go
  service/http/errors_windows.go
  service/http/handler.go
  service/http/response.go
Labels: A-network, B-bug

#356 Attempt to fix npe in the StaticPool mutex
  static_pool.go
Labels: B-regression
