Repository roadrunner-server/roadrunner, pull requests merged in 2020-10, with the labels that each got.

#365 Create codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
Labels: A-other

#371 Rpc roadrunner endure plugin
  .github/workflows/ci-build.yml
  bors.toml
  pipe_factory_test.go
  plugins/config/tests/config_test.go
  plugins/config/viper.go
  plugins/factory/app.go
  plugins/factory/tests/factory_test.go
  plugins/rpc/config.go
  plugins/rpc/config_test.go
  plugins/rpc/doc/plugin_arch.drawio
  plugins/rpc/rpc.go
  plugins/rpc/rpc_test.go
  pool.go
  pool_supervisor.go
  socket_factory_test.go
  static_pool.go
  static_pool_test.go
  sync_worker.go
Labels: A-module

#372 Release 1.8.4
  CHANGELOG.md
  build.sh
  go.mod
  go.sum
Labels: C-enhancement

#373 Feature/new worker produces active worker
  errors.go
  errors/go.mod
  errors_test.go
  go.mod
  go.sum
  pipe_factory_test.go
  plugins/config/provider.go
  plugins/config/tests/config_test.go
  plugins/config/viper.go
  plugins/events/broadcaster.go
  plugins/factory/app.go
  plugins/factory/app_provider.go
  plugins/factory/config.go
  plugins/factory/factory.go
  plugins/factory/hello.php
  plugins/factory/tests/factory_test.go
  plugins/factory/tests/plugin_1.go
  plugins/factory/tests/plugin_2.go
  plugins/rpc/config.go
  plugins/rpc/rpc.go
  plugins/rpc/rpc_test.go
  pool.go
  pool_supervisor.go
  socket_factory.go
  socket_factory_test.go
  static_pool.go
  static_pool_test.go
  supervisor_pool.go
  sync_worker.go
  sync_worker_test.go
  util/events.go
  worker.go
  worker_test.go
  worker_watcher.go
Labels: A-module

#376 Feature/lazy load
  errors.go
  errors_test.go
  pool.go
  static_pool.go
  static_pool_test.go
  sync_worker.go
  sync_worker_test.go
  worker_watcher.go
Labels: C-enhancement

#377 Feature/pool supervisor
  .github/workflows/ci-build.yml
  composer.lock
  errors/errors.go
  errors/errors_test.go
  errors/go.mod
  errors/marshal.go
  pipe_factory.go
  plugins/factory/tests/plugin_2.go
  pool.go
  socket_factory.go
  state.go
  static_pool.go
  static_pool_test.go
  supervisor_pool.go
  supervisor_test.go
  sync_worker.go
  tests/memleak.php
  tests/sleep.php
  worker.go
  worker_test.go
  worker_watcher.go
Labels: A-module

#378 Feature/logging
  composer.json
  go.mod
  plugins/app/app.go
  plugins/app/config.go
  plugins/app/tests/.rr.yaml
  plugins/app/tests/factory_test.go
  plugins/app/tests/hello.php
  plugins/app/tests/plugin_1.go
  plugins/app/tests/plugin_2.go
  plugins/logger/config.go
  plugins/logger/encoder.go
  plugins/logger/zap_logger.go
  plugins/rpc/rpc.go
  src/Diactoros/ServerRequestFactory.php
  src/Diactoros/StreamFactory.php
  src/Diactoros/UploadedFileFactory.php
  src/Exception/RoadRunnerException.php
  src/Exceptions/RoadRunnerException.php
  src/Http/HttpClient.php
  src/Http/PSR7Client.php
  src/Logger/.empty
  src/Metrics/Metrics.php
  src/Metrics/MetricsInterface.php
  src/WorkerInterface.php
Labels: A-module

#379 collect app logs into single channel
  plugins/app/app.go
Labels: C-enhancement
