Repository roadrunner-server/roadrunner, pull requests merged in 2021-09, with the labels that each got.

#778 feat(refactor): jobs code adjusting
  .golangci.yml
  CHANGELOG.md
  Makefile
  common/kv/interface.go
  go.mod
  go.sum
  plugins/amqp/amqpjobs/consumer.go
  plugins/amqp/amqpjobs/item.go
  plugins/amqp/amqpjobs/redial.go
  plugins/beanstalk/consumer.go
  plugins/beanstalk/item.go
  plugins/boltdb/boltjobs/consumer.go
  plugins/boltdb/boltjobs/listener.go
  plugins/boltdb/boltkv/driver.go
  plugins/boltdb/doc/job_lifecycle.md
  plugins/boltdb/plugin.go
  plugins/ephemeral/plugin.go
  plugins/jobs/job/job.go
  plugins/jobs/job/job_test.go
  plugins/jobs/plugin.go
  plugins/jobs/rpc.go
  plugins/kv/plugin.go
  plugins/memcached/memcachedkv/config.go
  plugins/memcached/memcachedkv/driver.go
  plugins/memcached/plugin.go
  plugins/memory/memoryjobs/consumer.go
  plugins/memory/memoryjobs/item.go
  plugins/memory/memorykv/config.go
  plugins/memory/memorykv/kv.go
  plugins/memory/memorypubsub/pubsub.go
  plugins/memory/plugin.go
  plugins/redis/clients.go
  plugins/redis/interface.go
  plugins/redis/kv/kv.go
  plugins/sqs/consumer.go
  tests/plugins/jobs/beanstalk/.rr-beanstalk-jobs-err.yaml
  tests/plugins/jobs/configs/.rr-jobs-init.yaml
  tests/plugins/jobs/jobs_general_test.go
  tests/plugins/jobs/jobs_memory_test.go
  tests/plugins/jobs/memory/.rr-memory-declare.yaml
  tests/plugins/jobs/memory/.rr-memory-init.yaml
  tests/plugins/jobs/memory/.rr-memory-jobs-err.yaml
  tests/plugins/jobs/memory/.rr-memory-pause-resume.yaml
  tests/plugins/kv/configs/.rr-kv-bolt-no-interval.yaml
  tests/plugins/kv/configs/.rr-kv-bolt-perms.yaml
  tests/plugins/kv/configs/.rr-kv-init.yaml
  tests/plugins/redis/plugin1.go
  tests/plugins/redis/redis_plugin_test.go
  tests/plugins/rpc/configs/.rr-rpc-disabled.yaml
  tests/plugins/rpc/configs/.rr.yaml
Labels: C-enhancement, A-other, stable-nominated

#782 feat(logger): Zap fields can be used as arguments to logger
  plugins/logger/zap_adapter.go
  tests/plugins/logger/logger_test.go
  tests/plugins/logger/plugin.go
Labels: C-enhancement, A-logs

#792 bug(attributes): make `attributes.Init` idempotent
  CHANGELOG.md
  plugins/http/attributes/attributes.go
Labels: B-bug, B-regression, A-module

#795 fix(jobs, memory): start `jobs` `in-memory` driver automatically if the user consumes it
  .vscode/settings.json
  CHANGELOG.md
  plugins/memory/memoryjobs/consumer.go
  tests/plugins/jobs/jobs_memory_test.go
Labels: C-enhancement, A-module, stable-nominated

#793 fix(plugins, 💔 BC): incorrect parsing local and global drivers sections
  .vscode/settings.json
  CHANGELOG.md
  Makefile
  codecov.yml
  pkg/priority_queue/binary_heap_test.go
  pkg/transport/pipe/pipe_factory_test.go
  plugins/broadcast/config.go
  plugins/broadcast/plugin.go
  plugins/kv/plugin.go
  plugins/memcached/memcachedkv/driver.go
  plugins/memory/memoryjobs/consumer.go
  plugins/memory/memorykv/kv.go
  plugins/memory/memorypubsub/pubsub.go
  plugins/memory/plugin.go
  plugins/redis/jobs/config.go
  plugins/redis/jobs/consumer.go
  plugins/redis/jobs/item.go
  plugins/redis/kv/config.go
  plugins/redis/kv/kv.go
  plugins/redis/pubsub/pubsub.go
  tests/plugins/broadcast/configs/.rr-broadcast-config-error.yaml
  tests/plugins/broadcast/configs/.rr-broadcast-global.yaml
  tests/plugins/broadcast/configs/.rr-broadcast-init.yaml
  tests/plugins/broadcast/configs/.rr-broadcast-same-section.yaml
  tests/plugins/kv/configs/.rr-boltdb.yaml
  tests/plugins/kv/configs/.rr-in-memory.yaml
  tests/plugins/kv/configs/.rr-kv-bolt-no-interval.yaml
  tests/plugins/kv/configs/.rr-kv-bolt-perms.yaml
  tests/plugins/kv/configs/.rr-kv-init.yaml
  tests/plugins/kv/configs/.rr-memcached.yaml
  tests/plugins/kv/configs/.rr-redis-global.yaml
  tests/plugins/kv/configs/.rr-redis-no-config.yaml
  tests/plugins/kv/configs/.rr-redis.yaml
  tests/plugins/kv/storage_plugin_test.go
  tests/plugins/websockets/configs/.rr-websockets-allow.yaml
  tests/plugins/websockets/configs/.rr-websockets-allow2.yaml
  tests/plugins/websockets/configs/.rr-websockets-broker-no-section.yaml
  tests/plugins/websockets/configs/.rr-websockets-deny.yaml
  tests/plugins/websockets/configs/.rr-websockets-deny2.yaml
  tests/plugins/websockets/configs/.rr-websockets-init.yaml
  tests/plugins/websockets/configs/.rr-websockets-redis.yaml
  tests/plugins/websockets/configs/.rr-websockets-stop.yaml
Labels: B-regression, A-module, B-Breaking changes
