Repository roadrunner-server/roadrunner, pull requests merged in 2021-04, with the labels that each got.

#617 feat(log): add "raw" mode
  CHANGELOG.md
  go.mod
  go.sum
  plugins/logger/config.go
  plugins/server/plugin.go
  tests/plugins/http/http_plugin_test.go
  tests/plugins/logger/configs/.rr-raw-mode.yaml
  tests/plugins/logger/logger_test.go
  tests/plugins/logger/plugin.go
  tests/raw-error.php
Labels: A-logs

#623 🔥 feat(status): Readiness checks
  CHANGELOG.md
  go.mod
  go.sum
  pkg/transport/socket/socket_factory.go
  plugins/http/plugin.go
  plugins/status/config.go
  plugins/status/interface.go
  plugins/status/plugin.go
  plugins/status/rpc.go
  tests/plugins/config/config_test.go
  tests/plugins/config/plugin2.go
  tests/plugins/status/configs/.rr-ready-init.yaml
  tests/plugins/status/plugin_test.go
Labels: A-module, C-enhancement, P-High, beta-nominated, stable-nominated

#634 feat(plugin): new plugin `service`
  .github/workflows/linux.yml
  .gitignore
  CHANGELOG.md
  Makefile
  go.sum
  pkg/pool/static_pool.go
  pkg/pool/supervisor_pool.go
  pkg/process/state.go
  pkg/transport/interface.go
  pkg/worker/interface.go
  pkg/worker/state.go
  pkg/worker/worker.go
  plugins/http/plugin.go
  plugins/informer/interface.go
  plugins/informer/plugin.go
  plugins/informer/rpc.go
  plugins/logger/config.go
  plugins/logger/plugin.go
  plugins/service/config.go
  plugins/service/plugin.go
  plugins/service/process.go
  plugins/static/plugin.go
  tests/plugins/http/http_plugin_test.go
  tests/plugins/informer/informer_test.go
  tests/plugins/informer/test_plugin.go
  tests/plugins/service/configs/.rr-service-error.yaml
  tests/plugins/service/configs/.rr-service-init.yaml
  tests/plugins/service/configs/.rr-service-restarts.yaml
  tests/plugins/service/service_plugin_test.go
  tests/plugins/service/test_files/loop.php
  tests/plugins/service/test_files/test_binary
  tools/worker_table.go
Labels: A-module, C-enhancement

#638 fix(http): Make an Serve function in the `http` plugin asynchronous.
  CHANGELOG.md
  go.sum
  pkg/transport/pipe/pipe_factory.go
  plugins/http/plugin.go
  plugins/metrics/plugin.go
  tests/composer.json
  tests/metrics-issue-571.php
  tests/plugins/gzip/plugin_test.go
  tests/plugins/http/http_plugin_test.go
  tests/plugins/metrics/configs/.rr-issue-571.yaml
  tests/plugins/metrics/configs/.rr-test.yaml
  tests/plugins/metrics/metrics_test.go
  tests/plugins/reload/reload_plugin_test.go
Labels: C-enhancement

#643 feat(kv): kv plugin stabilization
  .github/workflows/linux.yml
  CHANGELOG.md
  Makefile
  go.mod
  go.sum
  plugins/config/interface.go
  plugins/config/plugin.go
  plugins/kv/boltdb/plugin_unit_test.go
  plugins/kv/config.go
  plugins/kv/doc/kv.drawio
  plugins/kv/drivers/boltdb/config.go
  plugins/kv/drivers/boltdb/driver.go
  plugins/kv/drivers/boltdb/plugin.go
  plugins/kv/drivers/memcached/config.go
  plugins/kv/drivers/memcached/driver.go
  plugins/kv/drivers/memcached/plugin.go
  plugins/kv/drivers/memory/config.go
  plugins/kv/drivers/memory/driver.go
  plugins/kv/drivers/memory/plugin.go
  plugins/kv/drivers/redis/config.go
  plugins/kv/drivers/redis/driver.go
  plugins/kv/drivers/redis/plugin.go
  plugins/kv/interface.go
  plugins/kv/memcached/plugin_unit_test.go
  plugins/kv/memory/plugin_unit_test.go
  plugins/kv/payload/generated/Item.go
  plugins/kv/payload/generated/Payload.go
  plugins/kv/payload/payload.fbs
  plugins/kv/rpc.go
  plugins/kv/storage.go
  plugins/redis/interface.go
  plugins/resetter/plugin.go
  plugins/rpc/interface.go
  plugins/rpc/plugin.go
  tests/composer.json
  tests/docker-compose-full.yaml
  tests/docker-compose.yaml
  tests/plugins/kv/boltdb/configs/.rr-init.yaml
  tests/plugins/kv/boltdb/plugin_test.go
  tests/plugins/kv/configs/.rr-boltdb.yaml
  tests/plugins/kv/configs/.rr-in-memory.yaml
  tests/plugins/kv/configs/.rr-kv-init.yaml
  tests/plugins/kv/configs/.rr-memcached.yaml
  tests/plugins/kv/configs/.rr-redis.yaml
  tests/plugins/kv/memcached/configs/.rr-init.yaml
  tests/plugins/kv/memcached/plugin_test.go
  tests/plugins/kv/memory/configs/.rr-init.yaml
  tests/plugins/kv/memory/plugin_test.go
  tests/plugins/kv/storage_plugin_test.go
Labels: A-module, C-enhancement

#646 feat(static): completely rework `static` plugin
  .github/workflows/linux.yml
  CHANGELOG.md
  Makefile
  pkg/worker_watcher/worker_watcher.go
  plugins/gzip/plugin.go
  plugins/headers/plugin.go
  plugins/http/config/http.go
  plugins/http/config/static.go
  plugins/http/plugin.go
  plugins/http/serve.go
  plugins/http/static/etag.go
  plugins/http/static/static.go
  plugins/http/worker_handler/constants.go
  plugins/http/worker_handler/errors.go
  plugins/http/worker_handler/errors_windows.go
  plugins/http/worker_handler/handler.go
  plugins/http/worker_handler/parse.go
  plugins/http/worker_handler/request.go
  plugins/http/worker_handler/response.go
  plugins/http/worker_handler/uploads.go
  plugins/static/config.go
  plugins/static/plugin.go
  tests/plugins/http/configs/.rr-http-static-disabled.yaml
  tests/plugins/http/configs/.rr-http-static-etags.yaml
  tests/plugins/http/configs/.rr-http-static-files-disable.yaml
  tests/plugins/http/configs/.rr-http-static-files.yaml
  tests/plugins/http/configs/.rr-http-static-security.yaml
  tests/plugins/http/configs/.rr-http-static.yaml
  tests/plugins/http/handler_test.go
  tests/plugins/http/http_plugin_test.go
  tests/plugins/http/parse_test.go
  tests/plugins/http/plugin_middleware.go
  tests/plugins/http/response_test.go
  tests/plugins/http/uploads_test.go
  tests/plugins/static/config_test.go
  tests/plugins/static/static_plugin_test.go
  tests/sample.txt
  tests/static/sample.txt
Labels: A-module, C-enhancement

#651 fix(logger): remove redundant logger interface implementation
  CHANGELOG.md
  plugins/logger/plugin.go
Labels: B-regression, stable-nominated
