Repository roadrunner-server/roadrunner, pull requests merged in 2021-01, with the labels that each got.

#470 [RR2] Bugfix/missed pool events
  plugins/server/plugin.go
Labels: B-regression

#473 feat(env): Add RR system environment variables
  .rr.yaml
  codecov.yml
  pkg/pool/config.go
  pkg/pool/supervisor_pool.go
  pkg/pool/supervisor_test.go
  pkg/worker_watcher/worker_watcher.go
  plugins/config/interface.go
  plugins/config/plugin.go
  plugins/http/config.go
  plugins/kv/memcached/plugin_unit_test.go
  plugins/kv/memory/plugin_unit_test.go
  plugins/rpc/config.go
  plugins/rpc/plugin.go
  plugins/server/config.go
  plugins/server/plugin.go
  tests/plugins/config/.rr.yaml
  tests/plugins/config/config_test.go
  tests/plugins/config/plugin1.go
  tests/plugins/kv/boltdb/plugin_test.go
  tests/plugins/kv/memcached/plugin_test.go
  tests/plugins/kv/memory/plugin_test.go
  tests/plugins/rpc/configs/.rr-rpc-disabled.yaml
  tests/plugins/rpc/configs/.rr.yaml
Labels: A-other, C-enhancement

#475 1.9.2 release milestone
  .rr.yaml
  CHANGELOG.md
Labels: A-other

#476 fix(yaml): Use mapstructure structure tags instead of yaml
  .rr.yaml
  pkg/pool/config.go
  pkg/pool/static_pool.go
  plugins/http/config.go
  plugins/http/handler.go
  plugins/http/plugin.go
  plugins/kv/boltdb/config.go
  plugins/logger/config.go
  plugins/redis/config.go
  plugins/server/config.go
  plugins/server/plugin.go
  tests/plugins/config/plugin1.go
Labels: B-regression

#477 feat(worker_watcher): Add stack tests
  .github/workflows/build.yml
  .gitignore
  .rr.yaml
  .vscode/launch.json
  .vscode/settings.json
  Makefile
  codecov.yml
  pkg/pipe/pipe_factory_spawn_test.go
  pkg/socket/socket_factory_spawn_test.go
  pkg/worker_watcher/stack.go
  pkg/worker_watcher/stack_test.go
  pkg/worker_watcher/worker_watcher.go
  plugins/kv/boltdb/plugin_unit_test.go
  plugins/kv/memcached/plugin.go
  plugins/kv/memcached/plugin_unit_test.go
  plugins/kv/memory/plugin_unit_test.go
  plugins/server/config.go
  tests/plugins/checker/configs/.rr-checker-init.yaml
  tests/plugins/gzip/configs/.rr-http-middlewareNotExist.yaml
  tests/plugins/gzip/configs/.rr-http-withGzip.yaml
  tests/plugins/headers/configs/.rr-cors-headers.yaml
  tests/plugins/headers/configs/.rr-headers-init.yaml
  tests/plugins/headers/configs/.rr-req-headers.yaml
  tests/plugins/headers/configs/.rr-res-headers.yaml
  tests/plugins/http/configs/.rr-broken-pipes.yaml
  tests/plugins/http/configs/.rr-env.yaml
  tests/plugins/http/configs/.rr-fcgi-reqUri.yaml
  tests/plugins/http/configs/.rr-fcgi.yaml
  tests/plugins/http/configs/.rr-h2c.yaml
  tests/plugins/http/configs/.rr-http.yaml
  tests/plugins/http/configs/.rr-init.yaml
  tests/plugins/http/configs/.rr-resetter.yaml
  tests/plugins/http/configs/.rr-ssl-push.yaml
  tests/plugins/http/configs/.rr-ssl-redirect.yaml
  tests/plugins/http/configs/.rr-ssl.yaml
  tests/plugins/informer/.rr-informer.yaml
  tests/plugins/kv/boltdb/configs/.rr-init.yaml
  tests/plugins/kv/memcached/configs/.rr-init.yaml
  tests/plugins/kv/memory/configs/.rr-init.yaml
  tests/plugins/reload/configs/.rr-reload-2.yaml
  tests/plugins/reload/configs/.rr-reload-3.yaml
  tests/plugins/reload/configs/.rr-reload-4.yaml
  tests/plugins/reload/configs/.rr-reload.yaml
  tests/plugins/resetter/.rr-resetter.yaml
  tests/plugins/server/configs/.rr-no-app-section.yaml
  tests/plugins/server/configs/.rr-sockets.yaml
  tests/plugins/server/configs/.rr-tcp.yaml
  tests/plugins/server/configs/.rr-wrong-command.yaml
  tests/plugins/server/configs/.rr-wrong-relay.yaml
  tests/plugins/server/configs/.rr.yaml
  tests/plugins/static/configs/.rr-http-static-disabled.yaml
  tests/plugins/static/configs/.rr-http-static-files-disable.yaml
  tests/plugins/static/configs/.rr-http-static-files.yaml
  tests/plugins/static/configs/.rr-http-static.yaml
Labels: A-ci, A-tests

#483 bug(server): Incorrectly set environment variables
  pkg/pipe/pipe_factory_spawn_test.go
  plugins/http/plugin.go
  plugins/logger/plugin.go
  plugins/server/plugin.go
  tests/plugins/http/response_test.go
Labels: B-regression

#485 bug(http): NPE when config didn't contain HTTP section
  .changes
  .github/pull_request_template.md
  .github/workflows/build.yml
  Dockerfile
  pkg/pool/static_pool_test.go
  pkg/pool/supervisor_test.go
  pkg/worker_watcher/stack.go
  plugins/http/plugin.go
  tests/plugins/http/configs/.rr-no-http.yaml
  tests/plugins/http/http_plugin_test.go
Labels: B-regression

#486 refactor(http): Uniform debug message from the http hanlder
  Makefile
  cmd/cli/workers.go
  plugins/http/plugin.go
  tests/plugins/http/http_plugin_test.go
  tests/plugins/static/static_plugin_test.go
Labels: A-logs

#487 refactor(errors, logs): Uniform all errors operations, Update server log level of the server log messages
  Makefile
  cmd/cli/reset.go
  cmd/cli/serve.go
  cmd/cli/workers.go
  go.mod
  go.sum
  interfaces/events/pool_events.go
  internal/protocol.go
  pkg/pipe/pipe_factory.go
  pkg/pool/static_pool.go
  pkg/pool/supervisor_pool.go
  pkg/socket/socket_factory.go
  pkg/worker/sync_worker.go
  pkg/worker/worker.go
  pkg/worker_watcher/worker_watcher.go
  plugins/checker/plugin.go
  plugins/checker/rpc.go
  plugins/config/plugin.go
  plugins/headers/plugin.go
  plugins/http/handler.go
  plugins/http/plugin.go
  plugins/informer/plugin.go
  plugins/kv/boltdb/plugin.go
  plugins/kv/boltdb/plugin_unit_test.go
  plugins/kv/memcached/plugin.go
  plugins/kv/memory/plugin.go
  plugins/metrics/plugin.go
  plugins/metrics/rpc.go
  plugins/redis/plugin.go
  plugins/reload/config.go
  plugins/reload/plugin.go
  plugins/reload/watcher.go
  plugins/resetter/plugin.go
  plugins/server/plugin.go
  plugins/static/config.go
  plugins/static/plugin.go
  tests/plugins/config/plugin1.go
  tests/plugins/gzip/plugin_test.go
  tests/plugins/http/http_plugin_test.go
  tests/plugins/reload/reload_plugin_test.go
  tests/plugins/static/static_plugin_test.go
  tools/process.go
  utils/isolate.go
Labels: A-logs, A-tests

#491 ref(configs, debug): update configs, add debug server
  .gitignore
  .rr.yaml
  cmd/cli/root.go
  cmd/main.go
  pkg/worker/worker.go
  plugins/checker/plugin.go
  plugins/gzip/plugin.go
  plugins/headers/config.go
  plugins/headers/plugin.go
  plugins/http/config/fcgi.go
  plugins/http/config/http.go
  plugins/http/config/http2.go
  plugins/http/config/ip.go
  plugins/http/config/ssl.go
  plugins/http/config/uploads_config.go
  plugins/http/handler.go
  plugins/http/parse.go
  plugins/http/plugin.go
  plugins/http/request.go
  plugins/http/uploads.go
  plugins/kv/boltdb/config.go
  plugins/kv/boltdb/plugin.go
  plugins/kv/memcached/config.go
  plugins/kv/memcached/plugin.go
  plugins/kv/memory/config.go
  plugins/kv/memory/plugin.go
  plugins/kv/memory/plugin_unit_test.go
  plugins/logger/plugin.go
  plugins/metrics/config.go
  plugins/metrics/plugin.go
  plugins/redis/config.go
  plugins/redis/plugin.go
  plugins/reload/config.go
  plugins/reload/plugin.go
  plugins/rpc/plugin.go
  plugins/server/plugin.go
  plugins/static/config.go
  plugins/static/plugin.go
  tests/plugins/headers/configs/.rr-cors-headers.yaml
  tests/plugins/headers/configs/.rr-headers-init.yaml
  tests/plugins/headers/configs/.rr-req-headers.yaml
  tests/plugins/headers/configs/.rr-res-headers.yaml
  tests/plugins/http/configs/.rr-ssl.yaml
  tests/plugins/http/handler_test.go
  tests/plugins/http/uploads_config_test.go
  tests/plugins/http/uploads_test.go
  tests/plugins/static/config_test.go
  tests/psr-worker-bench.php
Labels: A-other, A-tests

#493 Cross-reference PHP codebase
  bin/rr
  composer.json
Labels: A-other

#494 feat(https): Allow https to listen on unix sockets
  .github/workflows/build.yml
  .rr.yaml
  Makefile
  plugins/http/config/http.go
  plugins/http/config/ssl.go
  plugins/http/config/ssl_config_test.go
  plugins/http/plugin.go
  tests/plugins/http/configs/.rr-fcgi-reqUri.yaml
  tests/plugins/http/configs/.rr-fcgi.yaml
  tests/plugins/http/configs/.rr-init.yaml
  tests/plugins/http/configs/.rr-ssl-push.yaml
  tests/plugins/http/configs/.rr-ssl-redirect.yaml
  tests/plugins/http/configs/.rr-ssl.yaml
  tests/plugins/http/http_plugin_test.go
  tests/plugins/rpc/config_test.go
  utils/network.go
  utils/network_windows.go
Labels: A-other, B-Breaking changes

#508 fix(tests): Remove the rest of the temporal
  dput.cf
  tests/docker-compose.yaml
Labels: A-tests

#512 fix(server): remove command limitaion
  plugins/server/plugin.go
Labels: A-module, A-other
