Repository roadrunner-server/roadrunner, pull requests merged in 2021-06, with the labels that each got.

#698 feat(ws): replace `json` with binary flatbuffers
  CHANGELOG.md
  go.mod
  go.sum
  pkg/pubsub/interface.go
  pkg/pubsub/message.fbs
  pkg/pubsub/message.go
  pkg/pubsub/message/Message.go
  pkg/pubsub/message/Messages.go
  plugins/memory/plugin.go
  plugins/redis/fanin.go
  plugins/redis/plugin.go
  plugins/websockets/plugin.go
  plugins/websockets/pool/workers_pool.go
  plugins/websockets/rpc.go
  plugins/websockets/storage/storage.go
  tests/plugins/websockets/websocket_plugin_test.go
Labels: A-module, C-enhancement

#699 fix(bug): return `nil` if there are no workers in the requested plugin
  CHANGELOG.md
  go.mod
  go.sum
  plugins/informer/plugin.go
  plugins/informer/rpc.go
  tests/plugins/informer/informer_test.go
Labels: B-regression

#700 fix(bug): do not write internal error to the users responseWriter
  CHANGELOG.md
  go.mod
  go.sum
  pkg/pool/static_pool.go
  pkg/worker/sync_worker.go
  pkg/worker/worker.go
  pkg/worker_handler/handler.go
  pkg/worker_handler/request.go
  pkg/worker_handler/response.go
  pkg/worker_watcher/worker_watcher.go
  plugins/http/config/http.go
  plugins/http/plugin.go
  plugins/server/plugin.go
  tests/issue659.php
  tests/plugins/http/configs/.rr-issue659.yaml
  tests/plugins/http/handler_test.go
  tests/plugins/http/http_plugin_test.go
  tests/plugins/http/uploads_test.go
Labels: B-bug

#702 fix(fcgi): use fcgi server in the `applyMiddlewares`
  CHANGELOG.md
  plugins/http/serve.go
  tests/plugins/http/configs/.rr-fcgi-reqUri.yaml
  tests/plugins/http/configs/.rr-fcgi.yaml
  tests/plugins/http/configs/.rr-http-static.yaml
  tests/plugins/http/http_plugin_test.go
Labels: B-crash

#705 feat(websockets): bug fixing and polishing
  go.mod
  go.sum
  pkg/bst/bst.go
  pkg/bst/interface.go
  pkg/pubsub/interface.go
  plugins/gzip/plugin.go
  plugins/http/plugin.go
  plugins/memory/plugin.go
  plugins/redis/fanin.go
  plugins/redis/plugin.go
  plugins/websockets/executor/executor.go
  plugins/websockets/plugin.go
  plugins/websockets/pool/workers_pool.go
Labels: A-module, C-enhancement

#706 feat(CI): add `Windows` github actions CI
  .github/workflows/linux.yml
  .github/workflows/windows.yml
  Makefile
  README.md
  pkg/bst/bst_test.go
  pkg/pubsub/interface.go
  plugins/websockets/storage/storage.go
  plugins/websockets/storage/storage_test.go
  tests/plugins/metrics/metrics_test.go
Labels: A-ci, C-enhancement

#709 feat(metrics): expose HTTP metrics
  .github/workflows/codeql-analysis.yml
  CHANGELOG.md
  pkg/worker_handler/handler.go
  plugins/http/metrics.go
  plugins/http/plugin.go
  plugins/metrics/plugin.go
  tests/plugins/metrics/configs/.rr-http-metrics.yaml
  tests/plugins/metrics/metrics_test.go
Labels: A-metrics, C-enhancement

#710 feat(metrics): make `workers_hanler` listener events async
  pkg/worker_handler/handler.go
Labels: A-metrics, C-enhancement

#712 feat(ws, kv): switch from the `flatbuffers` to the `protobuf`
  CHANGELOG.md
  go.mod
  go.sum
  pkg/proto/kv/v1beta/kv.pb.go
  pkg/proto/kv/v1beta/kv.proto
  pkg/proto/websockets/v1beta/websockets.pb.go
  pkg/proto/websockets/v1beta/websockets.proto
  pkg/pubsub/interface.go
  pkg/pubsub/message.fbs
  pkg/pubsub/message.go
  pkg/pubsub/message/Message.go
  pkg/pubsub/message/Messages.go
  plugins/kv/drivers/boltdb/driver.go
  plugins/kv/drivers/memcached/driver.go
  plugins/kv/drivers/memcached/plugin.go
  plugins/kv/drivers/memory/driver.go
  plugins/kv/drivers/redis/driver.go
  plugins/kv/interface.go
  plugins/kv/payload/generated/Item.go
  plugins/kv/payload/generated/Payload.go
  plugins/kv/payload/payload.fbs
  plugins/kv/rpc.go
  plugins/redis/fanin.go
  plugins/redis/plugin.go
  plugins/websockets/executor/executor.go
  plugins/websockets/memory/inMemory.go
  plugins/websockets/plugin.go
  plugins/websockets/pool/workers_pool.go
  plugins/websockets/rpc.go
  tests/plugins/kv/storage_plugin_test.go
  tests/plugins/websockets/websocket_plugin_test.go
Labels: A-module, A-network, C-enhancement

#713 feat(server): path scan for a potential file path
  .github/workflows/linux.yml
  .github/workflows/windows.yml
  CHANGELOG.md
  Makefile
  go.mod
  go.sum
  plugins/server/command.go
  plugins/server/command_test.go
  plugins/server/plugin.go
  tests/plugins/gzip/configs/.rr-http-middlewareNotExist.yaml
  tests/plugins/gzip/plugin_test.go
  tests/plugins/metrics/metrics_test.go
  tests/plugins/reload/reload_plugin_test.go
  tests/plugins/server/configs/.rr.yaml
  tests/plugins/server/plugin_pipes.go
  tests/plugins/server/server_plugin_test.go
Labels: A-module, C-enhancement

#715 feat(protocol): use protobuf for the `kv` and `websockets` RPC calls
  CHANGELOG.md
  go.mod
  go.sum
  pkg/proto/kv/v1beta/kv.pb.go
  pkg/proto/kv/v1beta/kv.proto
  pkg/proto/websockets/v1beta/websockets.pb.go
  pkg/proto/websockets/v1beta/websockets.proto
  plugins/kv/drivers/boltdb/driver.go
  plugins/kv/drivers/memcached/driver.go
  plugins/kv/drivers/memory/driver.go
  plugins/kv/drivers/redis/driver.go
  plugins/kv/interface.go
  plugins/kv/rpc.go
  plugins/websockets/rpc.go
  tests/plugins/kv/storage_plugin_test.go
  tests/plugins/websockets/websocket_plugin_test.go
Labels: A-module, A-network, C-enhancement

#722 feat(opt): `inuse_space` and `runtime.newobject` optimizations
  internal/protocol.go
  pkg/pool/static_pool_test.go
  pkg/transport/socket/socket_factory.go
  pkg/worker/state.go
  pkg/worker/sync_worker.go
  pkg/worker_watcher/container/vec.go
Labels: C-enhancement

#723 fix(redis, ws): redis driver not available
  codecov.yml
  go.mod
  go.sum
  pkg/pubsub/interface.go
  plugins/kv/drivers/boltdb/plugin.go
  plugins/kv/drivers/memcached/plugin.go
  plugins/kv/drivers/memory/plugin.go
  plugins/kv/drivers/redis/config.go
  plugins/kv/drivers/redis/plugin.go
  plugins/kv/interface.go
  plugins/kv/plugin.go
  plugins/memory/plugin.go
  plugins/memory/pubsub.go
  plugins/redis/clients.go
  plugins/redis/interface.go
  plugins/redis/kv.go
  plugins/redis/plugin.go
  plugins/redis/pubsub.go
  plugins/websockets/config.go
  plugins/websockets/plugin.go
  tests/plugins/kv/configs/.rr-redis-global.yaml
  tests/plugins/kv/configs/.rr-redis-no-config.yaml
  tests/plugins/kv/storage_plugin_test.go
  tests/plugins/redis/plugin1.go
  tests/plugins/websockets/configs/.rr-websockets-redis-memory-local.yaml
  tests/plugins/websockets/configs/.rr-websockets-redis-no-section.yaml
  tests/plugins/websockets/websocket_plugin_test.go
Labels: A-module, B-bug, B-missing feature

#724 fix(boltdb): fix boltdb permissions, interval, config bugs
  CHANGELOG.md
  plugins/kv/drivers/boltdb/config.go
  plugins/kv/drivers/boltdb/driver.go
  tests/plugins/kv/configs/.rr-kv-bolt-no-interval.yaml
  tests/plugins/kv/configs/.rr-kv-bolt-perms.yaml
  tests/plugins/kv/storage_plugin_test.go
Labels: B-regression

#725 feat(plugin): make `in-memory` plugin general for the KV and WS
  plugins/kv/drivers/memory/plugin.go
  plugins/memory/config.go
  plugins/memory/kv.go
  plugins/memory/plugin.go
  tests/plugins/kv/storage_plugin_test.go
Labels: A-metrics, C-enhancement

#730 bug(websockets): not properly checked request origin
  .github/workflows/linux.yml
  .github/workflows/windows.yml
  CHANGELOG.md
  Makefile
  plugins/websockets/config.go
  plugins/websockets/connection/connection.go
  plugins/websockets/executor/executor.go
  plugins/websockets/origin.go
  plugins/websockets/origin_test.go
  plugins/websockets/plugin.go
  plugins/websockets/pool/workers_pool.go
  plugins/websockets/wildcard.go
  tests/plugins/websockets/websocket_plugin_test.go
  tests/worker-origin.php
Labels: B-regression, C-enhancement

#736 feat(kv): `clear` RPC method which completely cleans storage
  .github/workflows/windows.yml
  CHANGELOG.md
  README.md
  plugins/kv/drivers/boltdb/driver.go
  plugins/kv/drivers/memcached/driver.go
  plugins/kv/interface.go
  plugins/kv/rpc.go
  plugins/memory/kv.go
  plugins/redis/kv.go
  tests/plugins/broadcast/broadcast_plugin_test.go
  tests/plugins/kv/storage_plugin_test.go
  tests/plugins/websockets/websocket_plugin_test.go
Labels: B-missing feature, C-enhancement, beta-nominated

#738 fix(allocator): workers were not reallocating when `exec_ttl` was hit
  CHANGELOG.md
  pkg/pool/static_pool.go
  pkg/pool/supervisor_pool.go
  pkg/pool/supervisor_test.go
  pkg/worker/sync_worker.go
  pkg/worker_watcher/container/interface.go
  pkg/worker_watcher/container/vec.go
  pkg/worker_watcher/worker_watcher.go
  tests/plugins/http/configs/.rr-http-supervised-pool.yaml
  tests/plugins/http/http_plugin_test.go
  tests/psr-worker-slow.php
Labels: B-performance, B-regression, P-Release blocker, beta-nominated, stable-nominated

#741 feat(release): `v2.3.1` release
  CHANGELOG.md
Labels: C-enhancement, stable-nominated
