Repository roadrunner-server/roadrunner, pull requests merged in 2021-02, with the labels that each got.

#516 fix(activities): Update temporal plugin
  .dockerignore
  .github/workflows/build.yaml
  cmd/go.mod
  cmd/go.sum
Labels: A-module, A-other

#519 Composer metapackage and binary removing
  bin/rr
  composer.json
Labels: A-other

#520 sunc(#519): Remove bin folder
  bin/rr
Labels: A-other

#522 bug(logger): Incorrect parsing of nested log levels
  .gitignore
  go.mod
  go.sum
  internal/state.go
  internal/state_test.go
  pkg/events/pool_events.go
  pkg/pool/static_pool.go
  pkg/pool/static_pool_test.go
  pkg/pool/supervisor_pool.go
  pkg/states/worker_states.go
  pkg/transport/pipe/pipe_factory.go
  pkg/transport/pipe/pipe_factory_spawn_test.go
  pkg/transport/pipe/pipe_factory_test.go
  pkg/transport/socket/socket_factory.go
  pkg/worker/sync_worker.go
  pkg/worker/worker.go
  pkg/worker_watcher/stack.go
  pkg/worker_watcher/worker_watcher.go
  plugins/logger/config.go
  plugins/logger/plugin.go
  plugins/rpc/plugin.go
  plugins/server/plugin.go
  tests/worker.php
Labels: B-missing feature, B-regression

#524 release: beta.23
  cmd/go.mod
  cmd/go.sum
Labels: A-other

#525 bug(screen,race): fix race and workers stdout to screen
  cmd/cli/reset.go
  cmd/cli/root.go
  cmd/cli/workers.go
Labels: A-other

#526 bug(leak): workers memory leak
  .github/workflows/codeql-analysis.yml
  .rr.yaml
  bors.toml
  pkg/events/worker_events.go
  pkg/pool/static_pool_test.go
  pkg/pool/supervisor_test.go
  pkg/states/worker_states.go
  pkg/transport/pipe/pipe_factory_spawn_test.go
  pkg/transport/pipe/pipe_factory_test.go
  pkg/transport/socket/socket_factory_spawn_test.go
  pkg/transport/socket/socket_factory_test.go
  pkg/worker/sync_worker.go
  pkg/worker/worker.go
  plugins/informer/rpc.go
  plugins/server/plugin.go
  tests/composer.json
  tests/plugins/http/http_plugin_test.go
  tests/plugins/reload/reload_plugin_test.go
Labels: A-other, A-tests, B-bug

#529 Release 25
  .dockerignore
  .github/dependabot.yml
  .github/workflows/codeql-analysis.yml
  .rr.yaml
  cmd/go.mod
  cmd/go.sum
Labels: A-other

#530 stabilization(RC): rc stabilization
  .github/workflows/linters.yml
  .github/workflows/linux.yml
  .github/workflows/macos.yml
  .rr.yaml
  Makefile
  README.md
  go.mod
  go.sum
  internal/protocol.go
  internal/state.go
  internal/state_test.go
  pkg/payload/payload.go
  pkg/pool/interface.go
  pkg/pool/static_pool.go
  pkg/pool/static_pool_test.go
  pkg/pool/supervisor_pool.go
  pkg/states/worker_states.go
  pkg/transport/pipe/pipe_factory.go
  pkg/transport/pipe/pipe_factory_spawn_test.go
  pkg/transport/pipe/pipe_factory_test.go
  pkg/transport/socket/socket_factory.go
  pkg/transport/socket/socket_factory_test.go
  pkg/worker/interface.go
  pkg/worker/state.go
  pkg/worker/state_test.go
  pkg/worker/sync_worker.go
  pkg/worker/worker.go
  pkg/worker_watcher/container/interface.go
  pkg/worker_watcher/container/stack.go
  pkg/worker_watcher/container/stack_test.go
  pkg/worker_watcher/container/vec.go
  pkg/worker_watcher/interface.go
  pkg/worker_watcher/worker_watcher.go
  plugins/http/config/http.go
  plugins/http/plugin.go
  plugins/kv/memcached/plugin.go
  plugins/server/plugin.go
  tests/composer.json
  tests/plugins/gzip/configs/.rr-http-withGzip.yaml
  tests/plugins/http/http_plugin_test.go
  tests/plugins/informer/test_plugin.go
  tests/plugins/server/server_plugin_test.go
  tests/psr-worker-bench.php
  tests/src/Activity/SimpleActivity.php
  tests/src/Client/StartNewWorkflow.php
  tests/src/Workflow/SagaWorkflow.php
Labels: A-other

#541 release: RC1
  README.md
  cmd/go.mod
  cmd/go.sum
Labels: A-other

#542 feat(composer): Actualize composer.json dependencies
  composer.json
Labels: A-other

#544 feat(config): Add support for the overwriting config values
  CHANGELOG.md
  pkg/pool/supervisor_test.go
  plugins/config/plugin.go
  tests/docker-compose-full.yaml
  tests/plugins/config/.rr.yaml
  tests/plugins/config/config_test.go
  tests/plugins/config/plugin2.go
Labels: A-module, B-missing feature, P-Release blocker

#546 feat(logger): Logger plugin now optional (config)
  .rr.yaml
  CHANGELOG.md
  pkg/pool/static_pool_test.go
  plugins/logger/config.go
  plugins/logger/plugin.go
  tests/plugins/logger/configs/.rr-no-logger.yaml
  tests/plugins/logger/configs/.rr-no-logger2.yaml
  tests/plugins/logger/configs/.rr.yaml
  tests/plugins/logger/logger_test.go
Labels: A-module, B-missing feature

#547 feat(config): Parse env variables in the config
  .rr.yaml
  CHANGELOG.md
  pkg/pool/supervisor_pool.go
  pkg/worker_watcher/worker_watcher.go
  plugins/config/plugin.go
  tests/docker-compose-full.yaml
  tests/plugins/config/config_test.go
  tests/plugins/config/configs/.rr-env.yaml
  tests/plugins/config/configs/.rr.yaml
Labels: A-module, B-missing feature, P-Release blocker

#548 release(RC.3): RC.3 release
  CHANGELOG.md
Labels: A-other

#550 fix(php): PHP tests to use latest signatures
  tests/broken.php
  tests/delay.php
  tests/echo.php
  tests/head.php
  tests/memleak.php
  tests/pid.php
  tests/plugins/server/socket.php
  tests/plugins/server/tcp.php
  tests/sleep.php
  tests/slow-pid.php
  tests/stop.php
Labels: B-regression

#559 fix(various): Small fixes before release
  .github/ISSUE_TEMPLATE/feature_request.md
  .rr.yaml
  CHANGELOG.md
  plugins/gzip/plugin.go
  plugins/http/plugin.go
  plugins/static/plugin.go
  plugins/status/config.go
  plugins/status/interface.go
  plugins/status/plugin.go
  plugins/status/rpc.go
  tests/plugins/checker/configs/.rr-checker-init.yaml
  tests/plugins/checker/plugin_test.go
  tests/plugins/gzip/plugin_test.go
  tests/plugins/http/http_plugin_test.go
  tests/plugins/static/static_plugin_test.go
Labels: B-regression, C-enhancement
