Repository roadrunner-server/roadrunner, pull requests merged in 2021-03, with the labels that each got.

#569 ⚡v2.0.0
  .rr.yaml
  CHANGELOG.md
  go.sum
  internal/protocol.go
  pkg/doc/README.md
  plugins/doc/graphviz.svg
  systemd/rr.service
  tools/worker_table.go
Labels: C-enhancement

#574 🐛 fix(bug): remove php command path validation
  .rr.yaml
  plugins/server/plugin.go
Labels: B-regression

#575 Dockerfile deletion
  Dockerfile
Labels: A-other

#580 ⚡ feat(release): release v2.0.1
  .github/dependabot.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/linters.yml
  .github/workflows/linux.yml
  .rr.yaml
  CHANGELOG.md
  bors.toml
  go.mod
  go.sum
Labels: C-enhancement

#590 Bump github.com/hashicorp/go-multierror from 1.1.0 to 1.1.1
  go.mod
  go.sum
Labels: dependencies

#591 fix(http): make a root_ca optional to start the SSL server
  .golangci.yml
  plugins/http/config/http.go
  plugins/http/config/ssl.go
  plugins/http/plugin.go
Labels: B-regression

#592 🆕 new(http plugin): HTTP/HTTPS/FCGI servers errors redirected to the RR logger under the Error log level
  CHANGELOG.md
  plugins/http/plugin.go
  plugins/logger/interface.go
  plugins/logger/std_log_adapter.go
  tests/plugins/http/configs/.rr-h2c.yaml
  tests/plugins/http/http_plugin_test.go
Labels: A-logs, A-module

#597 👷 correct(http): http internal redirect code changed from 307 to 308
  CHANGELOG.md
  plugins/http/config/http.go
  plugins/http/plugin.go
Labels: A-module

#598 👷 correct(http): http internal redirect code changed from 307 to 308
  CHANGELOG.md
  plugins/http/config/http.go
  plugins/http/plugin.go
Labels: A-module

#608 fix(metrics): remove statsProvider from metrics collectors sync.Map
  .github/workflows/linters.yml
  .github/workflows/linux.yml
  CHANGELOG.md
  plugins/metrics/plugin.go
  tests/plugins/metrics/.rr-test.yaml
  tests/plugins/metrics/metrics_test.go
Labels: A-module, beta-nominated

#615 🐛 fix(bug): slow last response when reached `max_jobs` limit
  .editorconfig
  .golangci.yml
  CHANGELOG.md
  go.sum
  pkg/pool/config.go
  pkg/pool/static_pool.go
  pkg/pool/static_pool_test.go
  pkg/pool/supervisor_pool.go
  pkg/transport/pipe/pipe_factory_spawn_test.go
  pkg/transport/pipe/pipe_factory_test.go
  pkg/transport/socket/socket_factory.go
  pkg/transport/socket/socket_factory_spawn_test.go
  pkg/transport/socket/socket_factory_test.go
  pkg/worker/state.go
  pkg/worker/sync_worker.go
  pkg/worker/worker.go
  pkg/worker_watcher/container/stack.go
  pkg/worker_watcher/container/stack_test.go
  pkg/worker_watcher/worker_watcher.go
  plugins/http/errors.go
  plugins/http/handler.go
  plugins/kv/boltdb/plugin.go
  plugins/logger/zap_adapter.go
  plugins/metrics/plugin.go
  plugins/reload/plugin.go
  plugins/reload/watcher.go
  tests/mocks/mock_log.go
  tests/plugins/http/handler_test.go
  tests/plugins/http/uploads_test.go
  tests/plugins/reload/reload_plugin_test.go
  utils/network.go
Labels: B-bug, B-regression, beta-nominated, stable-nominated

#618 feat(config): Add the ability to provide general configuration to every plugin
  CHANGELOG.md
  go.sum
  plugins/config/config.go
  plugins/config/interface.go
  plugins/config/plugin.go
  tests/plugins/config/config_test.go
  tests/plugins/config/plugin3.go
Labels: A-module, C-enhancement
