Repository roadrunner-server/roadrunner, pull requests merged in 2022-02, with the labels that each got.

#981 deps: update dependencies
  .github/workflows/tests.yml
  .grype.yaml
  CHANGELOG.md
  go.mod
  go.sum
Labels: C-enhancement, A-other

#988 feat: release `v2.7.6`
  CHANGELOG.md
  go.mod
  go.sum
Labels: C-enhancement, R-stable

#1007 bugfix release: `v2.7.8`
  CHANGELOG.md
  go.mod
  go.sum
Labels: C-enhancement, R-stable

#1010 bugfix release: `v2.7.9`
  go.mod
  go.sum
  internal/container/plugins.go
Labels: C-enhancement, R-stable

#1016 feat(config): update `.rr.yaml` and json schema
  .rr.yaml
  schemas/config/2.0.schema.json
Labels: C-enhancement, A-other

#1019 release: `v2.8.1`
  .github/workflows/codeql-analysis.yml
  .github/workflows/release.yml
  .github/workflows/release_grpc.yml
  .github/workflows/tests.yml
  CHANGELOG.md
  go.mod
  go.sum
Labels: C-enhancement, R-stable

#1020 feat(docker): migrate to the `trivy` action instead of `grype`
  .github/workflows/tests.yml
  .grype.yaml
Labels: C-enhancement, A-other

#1022 release: `v2.8.2`
  CHANGELOG.md
  go.mod
  go.sum
Labels: C-enhancement, A-other, R-stable
