Repository roadrunner-server/roadrunner, pull requests merged in 2022-11, with the labels that each got.

#1357 chore: update grpc default address
  .rr.yaml
Labels: A-docs

#1358 pre-release: `v2.12.0-rc.1`
  CHANGELOG.md
  go.sum
  schemas/config/2.0.schema.json
Labels: C-enhancement

#1375 release: `v2.12.0`
  .rr.yaml
  CHANGELOG.md
  go.sum
Labels: C-enhancement

#1377 chore: update deprecated `set-output`
  .github/workflows/codeql-analysis.yml
  .github/workflows/release.yml
  .github/workflows/release_dep.yml
  .github/workflows/release_grpc.yml
  .github/workflows/release_grpc_buf.yml
  .github/workflows/tests.yml
Labels: C-enhancement, A-ci
