Repository roadrunner-server/roadrunner, pull requests merged in 2023-01, with the labels that each got.

#1401 chore: fix the description of the `--silent` flag
  internal/cli/root.go
Labels: A-other

#1415 release: `v2.12.2`
  CHANGELOG.md
  go.mod
  go.sum
Labels: C-enhancement

#1416 feature: bash script to download the latest release
  download-latest.sh
  go.mod
  go.sum
Labels: C-enhancement

#1394 feature: `endure v2` support
  .github/workflows/release.yml
  .github/workflows/release_dep.yml
  .github/workflows/tests.yml
  Dockerfile
  README.md
  cmd/rr/main.go
  container/config.go
  container/config_test.go
  container/container.go
  container/container_test.go
  container/plugins.go
  container/test/endure_ok_error.yaml
  container/test/endure_ok_fatal.yaml
  go.mod
  go.sum
  internal/cli/jobs/command.go
  internal/cli/jobs/command_test.go
  internal/cli/reset/command.go
  internal/cli/reset/command_test.go
  internal/cli/root.go
  internal/cli/root_test.go
  internal/cli/serve/command.go
  internal/cli/serve/command_test.go
  internal/cli/stop/command_test.go
  internal/cli/workers/command.go
  internal/cli/workers/command_test.go
  internal/cli/workers/render.go
  internal/debug/server_test.go
  internal/rpc/client.go
  internal/rpc/client_test.go
  lib/roadrunner.go
  lib/roadrunner_test.go
Labels: C-enhancement, beta-nominated, R-beta

#1422 chore(bc): update `composer.json`
  composer.json
Labels: C-enhancement, A-other

#1423 chore: update feature-request.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
Labels: C-enhancement

#1430 pre-release: `v2023.1.0-alpha.1`
  .rr.yaml
  go.mod
  go.sum
Labels: C-enhancement
