Repository roadrunner-server/roadrunner, pull requests merged in 2023-08, with the labels that each got.

#1676 chore: actualize `JOBS` commands
  internal/cli/jobs/command.go
Labels: C-enhancement, A-docs, A-other, R-stable

#1671 feature: `sd_notify` support
  .golangci.yml
  container/config.go
  container/config_test.go
  internal/cli/reset/command.go
  internal/cli/root.go
  internal/cli/serve/command.go
  internal/cli/stop/command.go
  internal/sdnotify/sdnotify.go
  lib/roadrunner.go
Labels: C-enhancement

#1680 fix: test failures on darwin
  internal/rpc/client_test.go
  internal/rpc/test/config_rpc_conn_err.yaml
  internal/rpc/test/config_rpc_ok.yaml
Labels: C-enhancement

#1684 pre-release: `v2023.3.0-beta.1`
  .github/workflows/release.yml
  CHANGELOG.md
  container/config.go
  container/config_test.go
  container/container_test.go
  go.mod
  go.sum
Labels: C-enhancement, R-beta

#1700 pre-release: `v2023.3.0-beta.2`
  CHANGELOG.md
  go.mod
  go.sum
Labels: C-enhancement, R-beta
