Repository roadrunner-server/roadrunner, pull requests merged in 2023-11, with the labels that each got.

#1768 fix: Allow to use env variable in schema properties
  schemas/config/2.0.schema.json
  schemas/config/3.0.schema.json
Labels: C-enhancement

#1773 release: `v2023.3.4`
  CHANGELOG.md
  go.mod
  go.sum
Labels: R-stable

#1783 release: `v2023.3.5`
  .rr.yaml
  CHANGELOG.md
  go.mod
  go.sum
Labels: C-enhancement, R-stable

#1786 feature: support for the `ARM64` deb release
  .github/workflows/release_dep_aarch64.yml
  go.mod
  go.sum
Labels: A-ci, R-stable

#1796 release: `v2023.3.7`
  CHANGELOG.md
  go.mod
  go.sum
Labels: C-enhancement, R-stable
