Repository roadrunner-server/roadrunner, pull requests merged in 2024-02, with the labels that each got.

#1856 release: `v2023.3.10`
  .rr.yaml
  CHANGELOG.md
  go.mod
  go.sum
  schemas/config/3.0.schema.json
Labels: C-enhancement

#1869 Fixed composer installation in README.md
  README.md
Labels: C-enhancement, A-docs

#1871 release: `2023.3.11`
  CHANGELOG.md
  go.mod
  go.sum
  internal/cli/root_test.go
Labels: C-enhancement, A-other

#1882 release: `v2023.3.12`
  CHANGELOG.md
  go.mod
  go.sum
Labels: C-enhancement
